<a href="https://colab.research.google.com/github/shivanssharma/Deep-Learning-Practise-/blob/main/DL_1st_Assignment_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic things in pytorch

In [2]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [ ]:
a[1]

tensor(1.)

In [ ]:
float(a[1])

1.0

In [ ]:
a[2]=2
a

tensor([1., 1., 2.])

In [ ]:
points = torch.Tensor([4,5,6,7,8])
points

tensor([4., 5., 6., 7., 8.])

In [ ]:
float(points[0]),float (points[1])

(4.0, 5.0)

In [ ]:
points = torch.Tensor([[4,5,6,7,8],[7,5,4,3, 9]])
points

tensor([[4., 5., 6., 7., 8.],
        [7., 5., 4., 3., 9.]])

In [ ]:
points.shape

torch.Size([2, 5])

In [ ]:
points =torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
points[0,1]=4
points

tensor([[0., 4.],
        [0., 0.],
        [0., 0.]])

In [ ]:
img=torch.randn(3,5,5)
weights=torch.Tensor([0.32,0.213,0.2341])

In [ ]:
batch=torch.randn(2,3,4,4)      #here batch,channels,rows,columns are there
batch

tensor([[[[-9.4476e-01,  3.5945e-01,  9.0031e-01,  1.3934e+00],
          [ 2.1288e-01,  2.1527e-01,  2.1196e+00, -7.8091e-02],
          [-6.4556e-01, -1.4431e+00,  1.3933e+00,  1.0836e+00],
          [ 1.1605e-03, -5.4771e-01, -4.1803e-01,  1.7135e-01]],

         [[-2.1621e-01, -1.5357e-01, -7.2609e-01, -7.9537e-01],
          [ 2.0182e-01, -6.4836e-02,  2.0640e+00, -4.1242e-01],
          [ 2.2059e-01,  1.8693e+00,  1.1297e+00,  4.6805e-02],
          [ 2.0407e+00, -2.6072e-01, -1.3152e+00,  1.1218e+00]],

         [[-3.4655e-01,  2.5865e-01, -1.2335e+00, -6.3745e-01],
          [-4.1156e-01, -2.1283e+00,  1.9112e-01,  1.1414e+00],
          [-1.9262e-01,  1.1558e-01, -1.9829e+00,  7.3371e-01],
          [ 1.0272e+00,  1.1733e+00, -8.3327e-02, -1.8286e+00]]],


        [[[ 8.9235e-01,  1.0655e-01,  1.1155e+00,  9.6327e-01],
          [ 2.9946e-01,  1.1422e+00, -5.3627e-03, -9.5209e-01],
          [-1.4933e+00, -2.2574e+00,  1.3202e+00,  9.6172e-02],
          [ 1.2709e+00,  1.0382e

In [ ]:
image_naive=img.mean(-2)      #mean is taken for the second last dimenssion
batch_naive=batch.mean(-3)    #mean is taken for the 3rd last dimension
image_naive,batch_naive

(tensor([[-0.5701, -0.0669,  0.2427,  0.5573,  0.4492],
         [-0.5053,  0.2875,  0.4053, -0.1118,  0.2562],
         [ 0.0797,  0.5296,  0.0131, -1.1495,  1.0003]]),
 tensor([[[-5.0251e-01,  1.5484e-01, -3.5308e-01, -1.3139e-02],
          [ 1.0469e-03, -6.5928e-01,  1.4583e+00,  2.1695e-01],
          [-2.0586e-01,  1.8059e-01,  1.8002e-01,  6.2137e-01],
          [ 1.0230e+00,  1.2164e-01, -6.0551e-01, -1.7847e-01]],
 
         [[ 3.6031e-01, -4.2856e-01,  2.5280e-01, -6.2520e-01],
          [ 3.0925e-02,  3.5170e-01, -3.0437e-01, -2.1839e-01],
          [-9.0540e-01, -3.9647e-01, -5.9634e-01, -2.0626e-01],
          [ 1.4380e+00, -2.2285e-01, -1.5617e+00,  1.7878e-01]]]))

In [ ]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)         #before the weights cannot be multiplied but now (C,1,1)
img_weights = (img * unsqueezed_weights)                          # (C,1,1)*(C,H,W)=(C,H,W)
batch_weights = (batch * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 4, 4]), torch.Size([2, 3, 4, 4]), torch.Size([3, 1, 1]))

In [ ]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img, weights)       #here we are collapsing the channeland making h and w
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 4, 4])

In [ ]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])      #naming the dimension
weights_named

/tmp/ipython-input-40-2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /pytorch/c10/core/TensorImpl.h:1935.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [ ]:
img_named = img.refine_names(..., 'channels', 'rows', 'columns')        #naming diffrent dimensions
batch_named = batch.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 4, 4]) (None, 'channels', 'rows', 'columns')


In [ ]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [ ]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [ ]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

#Datatype

In [ ]:
short_points.dtype,double_points.dtype

(torch.int16, torch.float64)

In [ ]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [ ]:
short_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [ ]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

#The tensor API

In [3]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)      #it transpose the dimension
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

#Indexing into Storage

In [4]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()                    #storing in this in 1d

/tmp/ipython-input-4-2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [7]:
points_storage = points.storage()
points_storage[0]

4.0

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

#Views of another tensor’s storage

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()         #it will put in 1d and takes the index

2

In [13]:
second_point.size()

torch.Size([2])

In [14]:
second_point.shape

torch.Size([2])

In [15]:
points.stride()

(2, 1)

In [16]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()      #makes copy of [5.0, 3.0]
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

#Transposing without copying

In [20]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points_t = points.t()       #shortcut of transpose
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [22]:
id(points.storage()) == id(points_t.storage())

True

In [23]:
points.stride()

(2, 1)

In [24]:
points_t.stride()

(1, 2)

#Transposing in higher dimensions

In [26]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape,transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))